name: Close Jira Issue

on:
  issues:
    types: [closed]

permissions:
  issues: write

jobs:
  close-jira-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Jira
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}

      - name: Extract Jira Key from Title
        id: extract-jira
        run: |
          TITLE="${{ github.event.issue.title }}"
          JIRA_KEY=$(echo "$TITLE" | grep -oP '\((${{ vars.JIRA_PROJECT_KEY }}-[0-9]+)\)' | tr -d '()')
          if [ -z "$JIRA_KEY" ]; then
            echo "❌ No Jira key found in title"
            exit 0
          fi
          echo "jira_key=$JIRA_KEY" >> $GITHUB_OUTPUT
          echo "Found Jira key: $JIRA_KEY"

      - name: Transition Jira Issue to Done
        if: steps.extract-jira.outputs.jira_key != ''
        uses: atlassian/gajira-transition@v3
        with:
          issue: ${{ steps.extract-jira.outputs.jira_key }}
          transition: "완료"

      - name: Add Comment to Jira
        if: steps.extract-jira.outputs.jira_key != ''
        uses: atlassian/gajira-comment@v3
        with:
          issue: ${{ steps.extract-jira.outputs.jira_key }}
          comment: 'GitHub Issue closed: ${{ github.event.issue.html_url }}'
